### ISSUE TITLE
Incompatibility issue

### ISSUE THREAD

**Issue by gdeiana** [tchronis/MSE-Mathematica#30]
Dear Author, 
Thank you a lot for your work on MSE. 
I am experiencing an issue when trying to download the code (or the standalone zipped version). I get notified by windows about a virus threat inside the folder. Are you familiar with this issue by any chance?
Thanks again

**Comment by tchronis** [comment]
Dear @gdeiana ,

I am not aware of such an issue. I see a file named wc.exe committed 6 years ago. But everyone that has downloaded the code did not mention anything. This file is for counting the number of lines in a file fast. 

I have removed this file (I think it is not relevant to running the code).

Please download again from the master branch and please let me know if there are issues.

Regards,

Theodore

**Comment by gdeiana** [comment]
Dear @tchronis,
Thank you so much for your quick reply and fix.
I was able to download the zipped version perfectly now!
Probably it was just a weird windows issue.
Best regards,
Guido
